### ISSUE TITLE
Implement a mechanism that prevents public signup

### ISSUE THREAD

**Issue by tanius** [edgeryders/dynalist_companion#16]
Right now, "everyone" from the Internet can sign up. Of course spam users will use that once they find out :laughing: Also, everyone who signs up can get content snippets from an access protected Dynalist document, as they are e-mailed notifications with new items containing the tag they subscribed to (which they could also set to `#important` or a similar educated guess). So it's important to prevent the "general public" from signing up.

The right solution for this still has to be discussed (talk to @tanius). Options include:

1. A form field for a "shared secret" in the signup form, in addition to the password. The field would have an explanation with a link pointing to a specific Dynalist list item in the monitored Dynalist file. This way, the link and the shared secret in that list item is only accessible to users with access to the Dynalist file – and only these users can sign up successfully. This is quite simple and elegant, but it is not clear yet how this mechanism could work when starting to monitor multiple files for changes.

2. Requiring the signup e-mail address to appear among the e-mail addresses to which the monitored Dynalist file is shared. However, this reduces the user's flexibility compared with the current solution where the user can choose different e-mail addresses for the Dynalist and Dynalist Notify accounts. And again, it is not clear yet how this mechanism could work when starting to monitor multiple files for changes. Also, the e-mail addresses would have to be confirmed by letting the users click on a confirmation link.

**Comment by anuzement** [comment]
I found  'secret code' implantation in config file best so far.
Secret code can be later shared to the members (staff) who sign ups.

**Comment by tanius** [comment]
Good idea, please go ahead with that solution :) It keeps the software nicely general, independent of how that secret code is distributed for any one installation.

In our case, we can still copy&paste the secret code into the access protected Dynalist file for which the software manages the notifications.
