### ISSUE TITLE
Remove tags.json and tags_import.py

### ISSUE THREAD

**Issue by tanius** [edgeryders/dynalist_companion#56]
After fixing #46, it seems that the files `resources/tags.json` and `resources/tags_import.py` are no longer needed. If that is the case, we better remove them, to keep the code tidy and compact. They will always still be available in the git history, in case we want them back later.

(In addition, they are right now in a directory ignored via `.gitignore`; so they can't stay where they are anyway, because it's not a place for code files.)

**Comment by anuzement** [comment]
I forget to close this issue with last commit.
I am closing this issue manually.
